## **Continuation of NumPy Operations**

In [23]:
import numpy as np

* **Starting Array with Array**

"Array with array" indexing means you can use another array of indices to extract or modify specific elements. Works in 1D, 2D, and higher dimensions. Very useful for selecting multiple positions at once.

In [24]:
new_arr_I = np.arange(0,11)
new_arr_I

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
new_arr_I + new_arr_I # element-wise addition

# You can also do subtraction, multiplication, division, etc.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
# You can also do
new_arr_I + 1000
# and apply other math functions like subtraction, multiplication, division, square root, etc.

array([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [27]:
# let's move foward to some more advanced operations
new_arr_II = np.arange(0,6)
new_arr_II

array([0, 1, 2, 3, 4, 5])

In [28]:
np.sqrt(new_arr_II) # square root of each element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [29]:
np.exp(new_arr_II) # exponent of each element

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [30]:
np.max(new_arr_II) # maximum value in the array
# np.min(), np.mean(), np.median(), np.std() also work similarly

5

In [31]:
# You can also use trigonometric functions
np.sin(new_arr_II) # sine of each element (in radians)
# np.cos(), np.tan(), np.arcsin(), np.arccos(), np.arctan() also work similarly

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [32]:
np.log(new_arr_II) # natural logarithm of each element
# Here np.log(0) will return -inf (negative infinity) since the logarithm of zero is undefined

C:\Users\monin\AppData\Local\Temp\ipykernel_16284\3971796903.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(new_arr_II) # natural logarithm of each element


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

* You can also find a lot of relevant information through the following **link**: "\https://numpy.org/doc/stable/user/index.html#user"\ 

* **General summary:**

* Array with Array: operations between arrays.

* Array with Scalars: operations between an array and a single number.

* Ufuncs: optimized NumPy functions for mathematical, statistical, and trigonometric operations.