## **NumPy Arrays**

With NumPy, you can perform numerical operations much faster and more efficiently than with Python’s built-in lists. It provides support for arrays and high-performance mathematical functions. It is widely used in fields such as data science, machine learning, statistics, and image processing.

In [1]:
# Example:
lst1 = [1, 2, 3, 4, 5]

In [2]:
import numpy as np  
var = np.array(lst1)

print(var)

[1 2 3 4 5]


In [3]:
# If I want to assemble a matrix: 2D array
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

matrix_1_np = np.array(matrix_1)

print(matrix_1_np)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


* **Numpy `np.arange()`**

Is a function that generates evenly spaced values within a given range, similar to Python’s built-in `range()`, but it returns a NumPy array instead of a list.

In [4]:
# First, use arange to create an array of integers from 0 to 11 
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Now with step:
np.arange(0, 11, 2)  # start, stop, step

array([ 0,  2,  4,  6,  8, 10])

* **Creating Matrices**

In [6]:
# You can also create arrays of zeros, using NumPy function like np.zeros().
np.zeros((3, 4))  # 3 rows, 4 columns of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2, 5))   # 2 rows, 5 columns of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#np.random.rand(5, 5)  # 5x5 array of random numbers between 0 and 1 or you can specify any shape you want
np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1

array([[0.73660129, 0.78883577, 0.66053654],
       [0.31917952, 0.40266966, 0.43076797],
       [0.17725242, 0.82697718, 0.3151717 ]])

In [9]:
np.random.randn(3, 3)  # 3x3 array of random numbers from the standard normal distribution

array([[-0.56457027, -0.65399535,  0.44831298],
       [-2.17692255, -0.58322197, -0.33567921],
       [ 1.83354591, -0.24309589,  0.15696637]])

In [10]:
# 10 random integers between 0 and 100 with interger values
np.random.randint(0, 100, 10) # low, high, number of values

array([65, 75, 97, 26, 67, 20, 85, 45,  5, 35])

In [11]:
# You can also create np.linspace() arrays. 
np.linspace(0, 20, 15)  # start, stop, number of values

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [12]:
np.eye(3)  # 4x4 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# np.reshape arrays change shape of array without changing its data
arr = np.arange(0, 10) # 1D array with 25 elements
arr.reshape(2, 5)  # 2 rows, 5 columns     


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
arr.reshape(1, 10)  # 1 row, 10 columns

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
arr.reshape(10, 1)  # 10 rows, 1 column

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

* **Maximum and Minimum Numbers**

In [16]:
new_arr = np.arange(19, 26)
new_arr.max()  # maximum value in the array


25

In [17]:
new_arr.min()  # minimum value in the array

19

In [18]:
new_arr

array([19, 20, 21, 22, 23, 24, 25])

In [19]:
new_arr.argmax()  # index of maximum value in the array
# It 6 because 25 is the maximum value and its index is 6

6

In [20]:
new_arr.argmin()  # index of minimum value in the array
# It 0 because 19 is the minimum value and its index is 0

0

In [21]:
new_arr.shape  # shape of the array (number of elements in each dimension)

(7,)

In [22]:
new = new_arr.reshape(1, 7)  # reshape to 1 row, 7 columns
new # shape of the new array

array([[19, 20, 21, 22, 23, 24, 25]])

In [23]:
new.shape  # shape of the new array

(1, 7)

In [24]:
new_arr.dtype

dtype('int32')

In [25]:
from numpy.random import randint
randint(0, 100, 5) # start, stop, number of values
# Create a 1-D array of 5 random integers from 0 to 100

array([75, 58, 53, 56, 70])

In [26]:
randint(0,10) # single random integer from 0 to 10

0