## **Continuing with the NumPy Library.**

In [72]:
# Start:
import numpy as np

In [73]:
# Recapitulation
lst = np.arange(0,11)
print(lst)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [74]:
# For finding elements in a list/array
lst[4]  # indexing

4

In [75]:
# For finding multiple elements in a list/array
lst[1:5]  # slicing

array([1, 2, 3, 4])

In [76]:
# Another way to do this:  
lst[:7] # from start to index 7 (not included)

array([0, 1, 2, 3, 4, 5, 6])

In [77]:
# You can also do this:
lst[4:]  # from index 4 to the end

array([ 4,  5,  6,  7,  8,  9, 10])

In [78]:
# Continue with the lesson...
lst[0:4] = 50 # changing values in an array
lst

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# let's see the next example: slice arrays
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
slice_ar = ar[0:5]  #    
slice_ar

array([0, 1, 2, 3, 4])

In [81]:
slice_ar[:] = 55  # this changes the original array too!
slice_ar

array([55, 55, 55, 55, 55])

In [82]:
ar

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10])

In [83]:
# Now .copy() to avoid this
ar_copy = ar.copy() # this creates a copy of the array
ar_copy

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10])

In [84]:
# It's possible to do this:
ar_copy[:] = 99
ar_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [85]:
# Next, let's see how to index a 2D array
ar_mt = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 
ar_mt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
# Finding a specific element in a 2D array
ar_mt[0][0]

1

In [87]:
ar_mt[0]

array([1, 2, 3])

In [88]:
# You can also do this:
ar_mt[2,1]  # this is the preferred way

8

In [89]:
# This is very cool, because you can do this too:
ar_mt[:2,0:]  # rows 0 and 1, all columns

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
# Another example
ar_mt[:1,1:]  # row 0, columns 1 and 2

array([[2, 3]])

* Next topic: Comparison with Operators

In [91]:
new_arr = np.arange(1,11)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
exp = new_arr > 7  # this returns a boolean array
exp 

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [93]:
new_arr[exp] # this returns the values that satisfy the condition

array([ 8,  9, 10])

In [94]:
# You can also do this:
new_arr[new_arr > 7]  # this is the preferred way
# You can do this with multiple conditions too <, >, ==, etc.

array([ 8,  9, 10])

In [95]:
# Now, let's see how to do something new
new_arr = np.arange(20).reshape(4,5)  # reshape the array to 4 rows and 5 columns
new_arr
# np.arange(n).reshape(r, c). Creates a sequence of numbers from 0 to n-1 and reshapes it into a matrix with r rows and c columns.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
new_arr[2, 2:3]  

array([12])

In [97]:
# Or this:
new_arr[2:, 3:]  # from row 2 and column 3 to the end

array([[13, 14],
       [18, 19]])

In [98]:
# It's possible to do this too:
new_arr[3, :2]  # row 3, columns 0 and 1

array([15, 16])

**|=>** There are many possibilities; you can experiment and practice visualizing your choices. Happy studying!