## **Some Examples Solved Using NumPy**

**|-> Example 1:** Import library NumPy.

In [94]:
import numpy as np

**|-> Example 2:** Create a array of 10 zeros.

In [95]:
zeros = np.zeros(10)
print(zeros)
# np.ones(10) to create an array of ones.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**|-> Example 3:**  Create an array of 10 number fives.

In [96]:
five = np.ones(10) * 5 # or np.full(10, 5) or np.ones(10) + 5
print(five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**|-> Example 4:** Create a array of the integers from 10 to 30.

In [97]:
np.arange(10, 31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

**|-> Example 5:** Create a array of all the even integers from 10 to 30.

In [98]:
np.arange(10, 31, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

**|-> Example 6:** Creat a 3x3 matrix with values ranging from 1 to 9.

In [99]:
matrix_1 = np.arange(1, 10).reshape(3, 3)
matrix_1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**|-> Example 7:** Creat a 3x3 indentity matrix.

In [100]:
matrix_2 = np.eye(3)
matrix_2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**|-> Example 8:** Generate a number between 0 and 1

In [101]:
np.random.rand(1) 

array([0.35568332])

**|-> Example 9:** Generate an array of 15 radom numbers sampled from a standad normal distribution.

In [102]:
matrix_3 = np.random.randn(15)
matrix_3

array([ 0.30334113, -0.76211078,  0.5139233 ,  0.62028583, -1.78448902,
        1.00116795,  1.27402275, -0.63487918, -0.13375754,  0.73052256,
        0.3498822 , -1.2075307 , -1.04251167,  0.46234283, -0.52235609])

**|-> Example 10:** Create a two-dimensional matrix of size 10 × 10 with numerical values between 0.01 and 1.00.


In [103]:

np.linspace(0.01, 1, 100).reshape(10, 10)

# Another way np.arange(1, 101).reshape(10, 10)/100 


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**|-> Example 10:** Let's create a matrix and perform some operations.

In [104]:
matrix_4 = np.arange(1, 26).reshape(5, 5) 

matrix_4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
# some operations
matrix_4.sum() # or np.sum(matrix_4)

325

In [106]:
# Subtration
matrix_4 - matrix_4


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [107]:
# multiplication
matrix_4 * matrix_4

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [108]:
# sen(matrix_4)
np.sin(matrix_4)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [109]:
np.std(matrix_4) # or np.var(matrix_4) 

7.211102550927978

In [110]:
# Get the sum of all the columns in matrix_4
matrix_4.sum(axis=0) # sum of all the columns in matrix_4

array([55, 60, 65, 70, 75])

In [111]:
matrix_4.sum(axis=1) # sum of all the rows in matrix_4

array([ 15,  40,  65,  90, 115])

**Well, see you later!**