## Continuing with the NumPy Library.

In [17]:
# Start:
import numpy as np

In [18]:
# Recapitulation
lst = np.arange(0,11)
print(lst)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
# For finding elements in a list/array
lst[4]  # indexing

4

In [20]:
# For finding multiple elements in a list/array
lst[1:5]  # slicing

array([1, 2, 3, 4])

In [21]:
# Another way to do this:  
lst[:7] # from start to index 7 (not included)

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
# You can also do this:
lst[4:]  # from index 4 to the end

array([ 4,  5,  6,  7,  8,  9, 10])

In [23]:
# Continue with the lesson...
lst[0:4] = 50 # changing values in an array
lst

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# let's see the next example: slice arrays
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
slice_ar = ar[0:5]  #    
slice_ar

array([0, 1, 2, 3, 4])

In [27]:
slice_ar[:] = 55  # this changes the original array too!
slice_ar

array([55, 55, 55, 55, 55])

In [28]:
ar

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10])